version: "3.4"
services:
  tdarr:
    container_name: tdarr_server
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      #- 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=${SERVER_IP}
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
      #- nodeID=MyInternalNode
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ./tdarr-server:/app/server
      - ${CONFIG_PATH}/tdarr:/app/configs
      - ${LOGS_PATH}/tdarr/:/app/logs
      - ${MEDIA_ROOT_PATH}/:/media
      - "/tmp/transcode_cache:/temp"

  tdarr-node:
    container_name: tdarr_node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeID=MainNode
      - serverIP=${SERVER_IP}
      - serverPort=8266
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/tdarr:/app/configs
      - ${LOGS_PATH}/tdarr/:/app/logs
      - ${MEDIA_ROOT_PATH}/:/media
      - "/tmp/transcode_cache:/temp"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
