version: '3'
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: media_emby
     env_file:
      - ./emby.env
    environment:
      - VIRTUAL_HOST=emby.lan
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/bundled-appdata/media-emby/emby/config:/config'
      - '/path/to/tvshows:/media/Shows'
      - '/path/to/movies:/media/Movies'
      - '/path/to/anime:/media/Anime'
    ports:
      - '8096:8096/tcp' # webpage http
      - '8920:8920/tcp' # webpage https/ssl
      - '1900:1900/udp' # dlna
      - '7359:7359/udp' # network discovery
    restart: unless-stopped

  jellyseerr:
    container_name: media_jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - '8955:5055' 
    env_file:
      - ./jellyseerr.env
    environment:
      - VIRTUAL_HOST=jellyseerr.lan
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/bundled-appdata/media-emby/jellyseerr/config:/app/config'
    networks:
      - media
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8965:8965 # webUI port
      - 8966:8266 # server port
      - 8967:8267 # Internal node port
      - 8968:8268 # Example extra node port
    env_file:
      - ./tdarr.env
    environment:
      - VIRTUAL_HOST=tdarr.lan
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8966
      - webUIPort=8965
      - internalNode=true
      - nodeID=MyInternalNode
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/bundled-appdata/media-emby/tdarr/server:/app/server'
      - '/opt/bundled-appdata/media-emby/tdarr/configs:/app/configs'
      - '/opt/bundled-appdata/media-emby/tdarr/logs:/app/logs'
      - '/media:/media'
      - '/tmp/transcode_cache:/temp'
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    env_file:
      - ./tdarr.env
    environment:
      - UMASK_SET=002
      - nodeID=MainNode
      - serverPort=8966
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/bundled-appdata/media-emby/tdarr/configs:/app/configs'
      - '/opt/bundled-appdata/media-emby/tdarr/logs:/app/logs'
      - '/media:/media'
      - '/tmp/transcode_cache:/temp'

networks:
  media:
    driver: bridge
    external: true