version: '3'
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: media_jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    env_file: .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/jellyfin:/config
      - ${MEDIA_ROOT_PATH}:/media
      - ${TRANSCODE_CACHE}/jellyfin-transcode-cache:/config/data/transcodes
    ports:
      - '8096:8096/tcp' # WebUI Port
      - '8920:8920/tcp' # webpage https/ssl
      - '1900:1900/udp' # dlna
      - '7359:7359/udp' # network discovery
    restart: unless-stopped
    networks:
      - media
    depends_on:
      - xteve
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  jellyseerr:
    container_name: media_jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - '8095:5055' # WebUI Port
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    env_file: .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/jellyseerr:/app/config
      - ${MEDIA_ROOT_PATH}:/media
      - '/tmp/transcode_cache:/config/data/transcodes'
    networks:
      - media
    depends_on:
      - jellyfin
      - radarr
      - sonarr
    restart: unless-stopped

  embystat:
    image: lscr.io/linuxserver/embystat:latest
    container_name: media_embystat
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    env_file: .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/embystat/:/config
    ports:
      - 6555:6555
    depends_on:
      - jellyfin
    restart: unless-stopped


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: media_radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    env_file: .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/radarr/:/config
      - ${MEDIA_ROOT_PATH}/Movies/:/movies
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 8093:7878 # WebUI & Service Port
    restart: unless-stopped
    networks:
      - media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: media_sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    env_file: .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/sonarr/:/config
      - ${MEDIA_ROOT_PATH}/Shows/:/Shows
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 8092:8989 # WebUI & Service Port
    restart: unless-stopped
    networks:
      - media
  xteve:
    container_name: media_xteve
    image: docker.io/alturismo/xteve:latest
    ports:
      - 34400:34400
    volumes:
      - ${CONFIG_PATH}/xtveve:/root/.xteve:rw
      - ${CONFIG_PATH}/xtveve/_config:/config:rw
      - /tmp/xteve/:/tmp/xteve:rw
      - ${CONFIG_PATH}/xtveve/tvheadend/data/:/TVH
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - media
networks:
  media:
    driver: bridge
    external: true
