version: '3'
secrets:
  plex_claim:
    external: true
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: media_plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM_FILE=/run/secrets/plex_claim
    secrets:
      - plex_claim
    env_file: .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/plex:/config
      - ${MEDIA_ROOT_PATH}:/media
    ports:
      - 32400:32400/tcp
      - 1900:1900/udp
      - 3005:3005/tcp
      - 5353:5353/udp
      - 8324:8324/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469/tcp
    restart: unless-stopped
    networks:
      - media
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  jellyseerr:
    container_name: media_jellyseerr
    image: docker.io/fallenbagel/jellyseerr:latest
    ports:
      - '8095:5055' # WebUI Port
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    env_file: .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/jellyseerr:/app/config
      - ${MEDIA_ROOT_PATH}:/media
      - '/tmp/transcode_cache:/config/data/transcodes'
    networks:
      - media
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: media_tautulli
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/tautulli:/app/config
    ports:
      - 6555:8181
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: media_radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    env_file: .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/radarr/:/config
      - ${MEDIA_ROOT_PATH}/Movies/:/movies
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 8093:7878 # WebUI & Service Port
    restart: unless-stopped
    networks:
      - media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: media_sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    env_file: .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ${CONFIG_PATH}/sonarr/:/config
      - ${MEDIA_ROOT_PATH}/Shows/:/Shows
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 8092:8989 # WebUI & Service Port
    restart: unless-stopped
    networks:
      - media

  xteve:
    container_name: media_xteve
    image: docker.io/alturismo/xteve:latest
    ports:
      - 34400:34400
    volumes:
      - ${CONFIG_PATH}/xtveve:/root/.xteve:rw
      - ${CONFIG_PATH}/xtveve/_config:/config:rw
      - /tmp/xteve/:/tmp/xteve:rw
      - ${CONFIG_PATH}/xtveve/tvheadend/data/:/TVH
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        
networks:
  media:
    driver: bridge
    external: true
